// Cross-version test vectors extracted from commit 21c5cfa0da1940acf8c2114bf251d04278710a95
//
// These test vectors were generated using:
// - Fixed static keys
// - Deterministic RNG (MockRng with sequential byte output)
// - Fixed timestamp: [0x40, 0x00, 0x00, 0x00, 0x5e, 0x0c, 0x93, 0x24, 0x12, 0x34, 0x56, 0x78]
// - MockRng seed 100 for device 1 (initiator)
// - MockRng seed 200 for device 2 (responder)
//
// The purpose of these tests is to verify that the new implementation produces
// byte-for-byte identical messages to the old implementation.

mod common;

use common::MockInstant;
use common::MockRng;
use rand_core::RngCore;
use wg_crypto::{Device, Initiation, Output, Response, SecretBytes, TAI64N, Timestamp};
use x25519_dalek::{PublicKey, StaticSecret};

// ============================================================================
// Test Configuration
// ============================================================================

/// Fixed static key for device 1 (initiator)
const SK1_BYTES: [u8; 32] = [
    0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
    0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10,
    0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18,
    0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20,
];

/// Expected public key for device 1
const PK1_BYTES: [u8; 32] = [
    0x07, 0xa3, 0x7c, 0xbc, 0x14, 0x20, 0x93, 0xc8,
    0xb7, 0x55, 0xdc, 0x1b, 0x10, 0xe8, 0x6c, 0xb4,
    0x26, 0x37, 0x4a, 0xd1, 0x6a, 0xa8, 0x53, 0xed,
    0x0b, 0xdf, 0xc0, 0xb2, 0xb8, 0x6d, 0x1c, 0x7c,
];

/// Fixed static key for device 2 (responder)
const SK2_BYTES: [u8; 32] = [
    0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28,
    0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f, 0x30,
    0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38,
    0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x3e, 0x3f, 0x40,
];

/// Expected public key for device 2
const PK2_BYTES: [u8; 32] = [
    0x58, 0x69, 0xaf, 0xf4, 0x50, 0x54, 0x97, 0x32,
    0xcb, 0xaa, 0xed, 0x5e, 0x5d, 0xf9, 0xb3, 0x0a,
    0x6d, 0xa3, 0x1c, 0xb0, 0xe5, 0x74, 0x2b, 0xad,
    0x5a, 0xd4, 0xa1, 0xa7, 0x68, 0xf1, 0xa6, 0x7b,
];

/// Pre-shared key
const PSK: [u8; 32] = [
    0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48,
    0x49, 0x4a, 0x4b, 0x4c, 0x4d, 0x4e, 0x4f, 0x50,
    0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58,
    0x59, 0x5a, 0x5b, 0x5c, 0x5d, 0x5e, 0x5f, 0x60,
];

/// Fixed timestamp used in old implementation (for documentation)
/// The actual timestamp is generated by FixedTimestamp from common module
const FIXED_TIMESTAMP_BYTES: [u8; 12] = [
    0x40, 0x00, 0x00, 0x00, 0x5e, 0x0c, 0x93, 0x24,  // TAI64 seconds
    0x12, 0x34, 0x56, 0x78,                          // nanoseconds
];

// ============================================================================
// Expected Test Vectors from Old Implementation
// ============================================================================

/// Expected initiation message (148 bytes)
/// Generated by device 1 (initiator) with RNG seed 100
const EXPECTED_INITIATION: &str = "\
01000000646566677e7c5c7029242d2c69a88b65a089dcdb61806bf92eb758b247df929ea18ac40ee25b919cfe3eb5b41da00e74aacdc99432ea8656259580138f493509a10e1e4124b69963539c71e99c7279dfbeb30dfb39cb01f182b48a9ea0d82b1d994576e2de258780733681a8e34c5e7506b565a5c958d6333f5af5e7074d185d00000000000000000000000000000000";

/// Expected response message (92 bytes)
/// Generated by device 2 (responder) with RNG seed 200
const EXPECTED_RESPONSE: &str = "\
02000000c8c9cacb64656667f0b33052377ed1269b8dc445e1718615f7c46141c114be3128bd1bfff019e12552413ab296c2f1b974e4217d31a45409331f8b4caba1365555aa1a2e1102ac3300000000000000000000000000000000";

/// Expected cookie reply (64 bytes)
/// Generated when MAC2 check fails
const EXPECTED_COOKIE_REPLY: &str = "\
0300000064656667c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedff4b69214aef2c3a464b4a21757cd0351f7218ddbde1c74f410e16b4502e2e288";

/// Expected initiator send key (responder recv key)
const EXPECTED_INITIATOR_SEND_KEY: &str = "ecd3a5e73607e80583f6f8c43cb340fa7f9a6107c968e969b0ab1b2290bc2a49";

/// Expected initiator recv key (responder send key)
const EXPECTED_INITIATOR_RECV_KEY: &str = "18a568259490fa0c3bf4de2fa521206a85e4ec811b75adc4619916a95d1973cc";

/// Expected initiator send ID
#[allow(dead_code)]
const EXPECTED_INITIATOR_SEND_ID: u32 = 3419064776;

/// Expected initiator recv ID
#[allow(dead_code)]
const EXPECTED_INITIATOR_RECV_ID: u32 = 1734763876;

// Note: MockRng, FixedTimestamp, and MockInstant are provided by the common module
// However, we need a custom FixedTimestamp that matches the old implementation's timestamp

/// Timestamp implementation that matches the old version
struct OldVersionTimestamp;

impl Timestamp for OldVersionTimestamp {
    fn generate() -> TAI64N {
        TAI64N(FIXED_TIMESTAMP_BYTES)
    }
}

// Message parsing uses the existing Initiation and Response structs from wg_crypto::messages

// ============================================================================
// Test Cases
// ============================================================================

#[test]
fn test_public_keys_match() {
    let sk1 = StaticSecret::from(SK1_BYTES);
    let pk1 = PublicKey::from(&sk1);
    assert_eq!(pk1.as_bytes(), &PK1_BYTES, "Public key 1 mismatch");

    let sk2 = StaticSecret::from(SK2_BYTES);
    let pk2 = PublicKey::from(&sk2);
    assert_eq!(pk2.as_bytes(), &PK2_BYTES, "Public key 2 mismatch");
}

#[test]
fn test_initiation_message_matches_old_version() {
    // Setup device 1 (initiator)
    let sk1 = StaticSecret::from(SK1_BYTES);
    let pk2 = PublicKey::from(PK2_BYTES);

    let mut dev1: Device<usize, MockInstant, OldVersionTimestamp> = Device::new();
    dev1.set_sk(Some(sk1));
    dev1.add(pk2, 1).unwrap();
    dev1.set_psk(pk2, SecretBytes(PSK)).unwrap();

    // Create initiation with deterministic RNG
    let mut rng = MockRng::new(100);
    let now = MockInstant::default();
    let msg_init = dev1.begin(now, &mut rng, &pk2).unwrap();

    // Compare with expected vector
    let expected_bytes = hex::decode(EXPECTED_INITIATION).unwrap();
    let expected = Initiation::parse(&expected_bytes[..]).unwrap();
    let actual = Initiation::parse(msg_init.as_ref()).unwrap();

    assert_eq!(*actual, *expected, "Initiation message mismatch\nExpected: {:#?}\nActual: {:#?}", *expected, *actual);
}

#[test]
fn test_response_message_matches_old_version() {
    // Setup device 2 (responder)
    let sk2 = StaticSecret::from(SK2_BYTES);
    let pk1 = PublicKey::from(PK1_BYTES);

    let mut dev2: Device<usize, MockInstant, OldVersionTimestamp> = Device::new();
    dev2.set_sk(Some(sk2));
    dev2.add(pk1, 2).unwrap();
    dev2.set_psk(pk1, SecretBytes(PSK)).unwrap();

    // Process initiation
    let initiation_bytes = hex::decode(EXPECTED_INITIATION).unwrap();
    let mut rng = MockRng::new(200);
    let now = MockInstant::default();

    let result = dev2.process(now, &mut rng, &initiation_bytes, None);

    assert!(result.is_ok(), "Failed to process initiation: {:?}", result.err());

    let Output { id: _, msg, key_pair } = result.unwrap();

    // Verify we got a response message
    assert!(msg.is_some(), "No response message generated");

    if let Some(msg_response) = msg {
        let expected_bytes = hex::decode(EXPECTED_RESPONSE).unwrap();
        let expected = Response::parse(&expected_bytes[..]).unwrap();
        let actual = Response::parse(msg_response.as_ref()).unwrap();

        assert_eq!(*actual, *expected, "Response message mismatch\nExpected: {:#?}\nActual: {:#?}", *expected, *actual);
    }

    // Verify keypair was created
    assert!(key_pair.is_some(), "No keypair generated");

    if let Some(kp) = key_pair {
        assert_eq!(kp.initiator, false, "Responder keypair should have initiator=false");

        let send_key_hex = hex::encode(kp.send.key.as_ref());
        let recv_key_hex = hex::encode(kp.recv.key.as_ref());

        assert_eq!(
            send_key_hex, EXPECTED_INITIATOR_RECV_KEY,
            "Responder send key mismatch"
        );
        assert_eq!(
            recv_key_hex, EXPECTED_INITIATOR_SEND_KEY,
            "Responder recv key mismatch"
        );
    }
}

#[test]
fn test_complete_handshake_matches_old_version() {
    // Setup device 1 (initiator)
    let sk1 = StaticSecret::from(SK1_BYTES);
    let pk1 = PublicKey::from(&sk1);
    let pk2 = PublicKey::from(PK2_BYTES);

    let mut dev1: Device<usize, MockInstant, OldVersionTimestamp> = Device::new();
    dev1.set_sk(Some(sk1));
    dev1.add(pk2, 1).unwrap();
    dev1.set_psk(pk2, SecretBytes(PSK)).unwrap();

    // Setup device 2 (responder)
    let sk2 = StaticSecret::from(SK2_BYTES);

    let mut dev2: Device<usize, MockInstant, OldVersionTimestamp> = Device::new();
    dev2.set_sk(Some(sk2));
    dev2.add(pk1, 2).unwrap();
    dev2.set_psk(pk1, SecretBytes(PSK)).unwrap();

    let now = MockInstant::default();

    // Step 1: Create initiation
    let mut rng1 = MockRng::new(100);
    let msg_init = dev1.begin(now, &mut rng1, &pk2).unwrap();

    let expected_init_bytes = hex::decode(EXPECTED_INITIATION).unwrap();
    let expected_init = Initiation::parse(&expected_init_bytes[..]).unwrap();
    let actual_init = Initiation::parse(msg_init.as_ref()).unwrap();

    assert_eq!(*actual_init, *expected_init, "Initiation mismatch\nExpected: {:#?}\nActual: {:#?}", *expected_init, *actual_init);

    // Step 2: Process initiation and create response
    let mut rng2 = MockRng::new(200);
    let Output { id: _id2, msg: msg_opt, key_pair: kp2 } =
        dev2.process(now, &mut rng2, msg_init.as_ref(), None).unwrap();

    assert!(msg_opt.is_some(), "No response message");
    let msg_response = msg_opt.unwrap();

    let expected_response_bytes = hex::decode(EXPECTED_RESPONSE).unwrap();
    let expected_response = Response::parse(&expected_response_bytes[..]).unwrap();
    let actual_response = Response::parse(msg_response.as_ref()).unwrap();

    assert_eq!(*actual_response, *expected_response, "Response mismatch\nExpected: {:#?}\nActual: {:#?}", *expected_response, *actual_response);

    assert!(kp2.is_some(), "Responder keypair not created");
    let kp2 = kp2.unwrap();
    assert_eq!(kp2.initiator, false);

    // Step 3: Process response
    let Output { id: _id1, msg: msg_opt, key_pair: kp1 } =
        dev1.process(now, &mut rng1, msg_response.as_ref(), None).unwrap();

    assert!(msg_opt.is_none(), "Unexpected message after processing response");
    assert!(kp1.is_some(), "Initiator keypair not created");
    let kp1 = kp1.unwrap();
    assert_eq!(kp1.initiator, true);

    // Verify keys match
    assert_eq!(kp1.send.key.as_ref(), kp2.recv.key.as_ref(), "Send/recv key mismatch (initiator->responder)");
    assert_eq!(kp1.recv.key.as_ref(), kp2.send.key.as_ref(), "Send/recv key mismatch (responder->initiator)");

    // Verify IDs match
    assert_eq!(kp1.send.id, kp2.recv.id, "Send/recv ID mismatch (initiator->responder)");
    assert_eq!(kp1.recv.id, kp2.send.id, "Send/recv ID mismatch (responder->initiator)");

    // Verify against expected values
    assert_eq!(
        hex::encode(kp1.send.key.as_ref()),
        EXPECTED_INITIATOR_SEND_KEY,
        "Initiator send key mismatch"
    );
    assert_eq!(
        hex::encode(kp1.recv.key.as_ref()),
        EXPECTED_INITIATOR_RECV_KEY,
        "Initiator recv key mismatch"
    );
}

#[test]
fn test_cookie_reply_matches_old_version() {
    // Note: Cookie reply generation in the new version may differ due to:
    // 1. Different MAC generation logic
    // 2. Different cookie key generation
    // 3. Source address handling
    //
    // This test documents the expected cookie reply from the old version
    // but may not pass if the new version has intentional differences.

    println!("Expected cookie reply from old version:");
    println!("{}", EXPECTED_COOKIE_REPLY);

    // This is a documentation test - actual cookie reply testing
    // would require providing a source address and triggering MAC2 failure
}

#[test]
fn test_deterministic_rng() {
    let mut rng1 = MockRng::new(100);
    let mut rng2 = MockRng::new(100);

    let mut buf1 = [0u8; 32];
    let mut buf2 = [0u8; 32];

    rng1.fill_bytes(&mut buf1);
    rng2.fill_bytes(&mut buf2);

    assert_eq!(buf1, buf2, "MockRng should be deterministic");

    // Verify first few bytes are sequential starting from 100
    assert_eq!(buf1[0], 100);
    assert_eq!(buf1[1], 101);
    assert_eq!(buf1[2], 102);
}

#[test]
fn test_fixed_timestamp() {
    let ts1 = OldVersionTimestamp::generate();
    let ts2 = OldVersionTimestamp::generate();

    assert!(ts1 == ts2, "OldVersionTimestamp should always return same value");
    assert_eq!(ts1.0, FIXED_TIMESTAMP_BYTES, "OldVersionTimestamp should match expected value");
}
