[Interface]
PrivateKey = qGi8YNkHHF4iXM5PtFGZQOGvwXRgqODDFnPwK6FpU0Y=
Address = 10.100.0.1/24
ListenPort = 51820

[Peer]
PublicKey = uCrkYqFHWhh1xFEZuDD/FoqVaV7i/3y2b723imaTrls=
AllowedIPs = 10.100.0.2/32
