name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Install cargo-hack
      run: cargo install cargo-hack --locked || [ -f ~/.cargo/bin/cargo-hack ]
    - name: Install just
      uses: extractions/setup-just@v2
    - name: Install WireGuard tools (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y wireguard-tools
    - name: Run Continuous Integration Checks (Linux)
      id: ci_linux
      if: runner.os == 'Linux'
      run: just ci
    - name: Run Continuous Integration Checks (macOS)
      if: runner.os == 'macOS'
      run: just build check-fmt test
    - name: Save CI log (Linux)
      if: failure() && steps.ci_linux.conclusion == 'failure' && runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: wg_client.log
        path: /tmp/wg_client.log
        retention-days: 7
